#! /bin/bash
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=17 where \"addr:interpolation\" is not null;"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where \"natural\" = 'tree_row';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where railway = 'platform';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where railway = 'turntable';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where highway = 'platform';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where power = 'minor_line';"
#append
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=16 where barrier is not null;"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=15 where railway = 'tram' and service in ('spur', 'siding', 'yard');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=15 where railway = 'disused';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=15 where man_made = 'embankment';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=15 where railway = 'miniature';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=14 where historic = 'citywalls';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=14 where man_made = 'cutline';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=14 where railway = 'monorail';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=14 where power = 'line';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=14 where waterway IN ('river', 'canal', 'derelict_canal', 'stream', 'drain', 'ditch', 'wadi') AND bridge IN ('yes', 'aqueduct');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'cycleway' or ( highway='path' and bicycle = 'designated');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'service';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'footway' or (highway = 'path' and bicycle != 'designated' and horse != 'designated');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'path' and bicycle is null and horse is null;"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where railway = 'preserved';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'track';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where railway = 'rail' and service in ('spur', 'siding', 'yard');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where railway = 'construction';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'pedestrian';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'living_street';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'steps';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'bridleway' or (highway = 'path' and horse = 'designated');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where waterway = 'stream' or waterway = 'ditch' or waterway = 'drain';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where waterway = 'wadi' and (bridge is null or bridge not in ('yes', 'aqueduct'));"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where \"natural\" = 'cliff';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'bus_guideway' and (tunnel is null or tunnel != 'yes');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where boundary = 'administrative' and (admin_level = '9' or admin_level = '10');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where waterway = 'dam' or  waterway = 'weir' or waterway = 'lock_gate';"
#append
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=13 where highway = 'path';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where railway = 'tram';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where man_made = 'pier' or man_made = 'breakwater' or man_made = 'groyne';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where aerialway = 'cable_car' or aerialway = 'gondola';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where highway = 'construction';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where highway = 'raceway';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where railway = 'subway';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where railway = 'preserved';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where aerialway = 'goods';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where railway = 'preserved' and service in ('spur', 'siding', 'yard');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where aerialway = 'chair_lift' or aerialway = 'drag_lift' or aerialway = 't-bar' or aerialway = 'j-bar' or aerialway = 'platter' or aerialway = 'rope_tow';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where waterway = 'canal'  and (bridge is null or bridge not in ('yes', 'aqueduct'));"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where highway = 'unclassified';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where highway = 'residential';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where boundary = 'administrative' and (admin_level = '7' or admin_level = '8');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=12 where waterway = 'derelict_canal' and (bridge is null or bridge not in ('yes', 'aqueduct'));"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=11 where aeroway = 'runway';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=11 where aeroway = 'taxiway';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=11 where boundary = 'administrative' and (admin_level = '5' or admin_level = '6');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=10 where highway = 'road';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=10 where highway = 'tertiary' or highway = 'tertiary_link';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=9 where highway = 'secondary' or highway = 'secondary_link';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=8 where highway = 'primary' or highway = 'primary_link';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=8 where railway = 'light_rail' or railway = 'funicular' or railway = 'narrow_gauge';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=8 where waterway = 'river';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=7 where route = 'ferry';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=7 where railway = 'rail';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=5 where highway = 'motorway' or highway = 'motorway_link';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=5 where highway = 'trunk' or highway = 'trunk_link';"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=4 where boundary = 'administrative' and (admin_level = '2' or admin_level = '3');"
psql -d osm_beijing -U postgres -c "update planet_osm_line set minzoom=4 where boundary = 'administrative' and admin_level = '4';"
